# Generated by Django 4.1.7 on 2023-03-01 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='keyword',
            new_name='ProductKeyword',
        ),
        migrations.AlterModelTable(
            name='momoshop',
            table=None,
        ),
        migrations.AlterModelTable(
            name='productkeyword',
            table=None,
        ),
    ]
