# Generated by Django 4.1.7 on 2023-03-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_rename_keyword_productkeyword_alter_momoshop_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('specification', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('price_min', models.CharField(max_length=200)),
                ('price_max', models.CharField(max_length=200)),
                ('historical_sold', models.CharField(max_length=50)),
            ],
        ),
    ]
